/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testAppExists() {
        try {
            Class.forName("sample.app.App");
        } catch (ClassNotFoundException e) {
            fail("Should have a class named App.");
        }
    }
}
