/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.app;

import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.Bucket;

import java.util.List;
import java.util.Date;
import java.text.SimpleDateFormat;

public class App {
    public static void main(String[] args) {
        SimpleDateFormat df = new SimpleDateFormat("yyyy MM dd");
        final AmazonS3 s3 = AmazonS3ClientBuilder.standard().withRegion(Regions.DEFAULT_REGION).build();
        List<Bucket> buckets = s3.listBuckets();
        for (Bucket b : buckets) {
            Date createDate = b.getCreationDate();
            var dateString = df.format(createDate);
            System.out.println(dateString + ", " + b.getName());
        }
    }
}
